package ${schema.defaultJavaPackage}.dagger.module;

import ${entity.javaPackageDao}.DaoMaster;
import ${entity.javaPackageDao}.DaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
<#list schema.entities as entity>
import ${entity.javaPackageDao}.${entity.classNameDao};
</#list>

import dagger.Module;
import dagger.Provides;

/**
 * Class generated by greenDao

 * Created by yinzara on 8/13/15.
 */
@Module
public class DaoModule {

    @Provides
    DaoSession provideDaoSession(DaoMaster master) {
        return master.newSession(IdentityScopeType.None);
    }

    //All of the DAOs

<#list schema.entities as entity>
    @Provides
    ${entity.classNameDao} provide${entity.classNameDao}(DaoSession session) {
        return session.get${entity.classNameDao}();
    }

</#list>
}