package ${schema.defaultJavaPackageEvent};

import android.os.Parcelable;

import ${entity.javaPackage}.${entity.className};
import ${schema.defaultJavaPackageEvent}.base.BaseEntityEvent;

/**
 * Generated by greenDao by a modification by Matthew Morrissette (yinzara@gmail.com)
 */
public class ${entity.className}Event extends BaseEntityEvent<${entity.className}> implements Parcelable {
    public static final Parcelable.Creator<${entity.className}Event> CREATOR = BaseEntityEvent.newCreator(${entity.className}Event.class, ${entity.className}.class);
}