package ${schema.defaultJavaPackage}.view.adapter;

import android.support.annotation.LayoutRes;
import android.content.Context;
import android.database.Cursor;
import ${schema.appPackage}.R;
import ${entity.javaPackageDao}.${entity.classNameDao};
import ${entity.javaPackage}.${entity.className};
import ${schema.defaultJavaPackage}.view.item.${entity.className}ListItemView;
import ${schema.appPackage}.view.base.adapter.BaseEntityBindableViewCursorAdapter;
import javax.inject.Inject;
import de.greenrobot.dao.internal.DaoConfig;

// KEEP INCLUDES - put your custom includes here
<#if keepIncludes?has_content>${keepIncludes!}</#if>// KEEP INCLUDES END

/**
 * Generated by greenDao
 *
 * Created by yinzara on 8/13/15.
 */
public class ${entity.className}CursorAdapter extends BaseEntityBindableViewCursorAdapter<${entity.className}, ${entity.className}ListItemView> {


    @Inject
    protected ${entity.classNameDao} _${entity.classNameDao};

    // KEEP FIELDS - put your custom fields here
    ${keepFields!}    // KEEP FIELDS END

    @Inject
    public ${entity.className}CursorAdapter(Context context) {
        super(context, R.layout.conversation_list_item_view);
    }

    public ${entity.className}CursorAdapter(Context context, @LayoutRes int layoutId) {
        super(context, layoutId);
    }

    @Override
    protected Cursor query() {
        return query(null);
    }

    @Override
    protected DaoConfig getDaoConfig() {
        return session.get${entity.classNameDao}Config();
    }

    // KEEP METHODS - put your custom methods here
    ${keepMethods!}    // KEEP METHODS END

}