package ${schema.defaultJavaPackageEvent};

import android.os.Parcelable;

import ${entity.javaPackage}.${entity.className};
import ${schema.defaultJavaPackageEvent}.base.BaseEntityListEvent;

/**
 * Generated by greenDao by a modification by Matthew Morrissette (yinzara@gmail.com)
 */
public class ${entity.className}ListEvent extends BaseEntityListEvent<${entity.className}> implements Parcelable {
    public static final Parcelable.Creator<${entity.className}ListEvent> CREATOR = BaseEntityListEvent.newCreator(${entity.className}ListEvent.class, ${entity.className}.class);

    public ${entity.className}ListEvent() {
        super(${entity.className}.class);
    }
}
